# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider :hyperv do |v|
        v.vmname  = "subversion-edge" 
    end

    config.vm.hostname = "subversion-edge"
    config.vm.network "public_network"
    config.vm.provider "hyperv"
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "./../../", "/vagrant", type: "smb"
    config.vm.provision :shell, path: "./../provision.sh"

    config.vm.network "forwarded_port", guest: 3343, host: 3343
    config.vm.network "forwarded_port", guest: 4434, host: 4434
    config.vm.network "forwarded_port", guest: 18080, host: 18080
end
